language: node_js
node_js:
  - 12
env:
  global:
    # 我将其添加到了travis-ci的环境变量中
    - GH_REF: github.com/zhangwang945/webpack-vue.git
after_script:
  - cd ./dist
  - git init
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:test
branches:
  only:
    - master
